env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  script:
    - ./configure || { cat config.log; exit 1; }
    - make
    - cd test
    - sh ./dotest
