env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  install_script:
    - pkg install -y autoconf
  build_script:
    - ./package/setup-configure
    - ./configure || { cat config.log; exit 1; }
    - make
  test_script:
    - make test

linux_gcc_task:
  container:
    image: gcc:latest
  build_script:
    - ./package/setup-configure
    - ./configure || { cat config.log; exit 1; }
    - make
  test_script:
    - make test
